In [3]:
import numpy as np 
a= np.array([1, 2, 3]) 
print("One dimensional array a = ",a) 
b = np.array([[1,2,3],[4,5,6]]) 
print("Two dimensional array b = ",b) 
print("Size of the array: ",a.shape) 
print("Element at indices 0,1,2: ",a[0], a [1], a[2]) 
a[0] = 5 
print("Array after changing the element at index 0: ",a) 
a = np.zeros((2,2))
print("An array of all zeros: ",a) 
b = np.ones((1,2)) 
print("An array of all ones: ",b) 
c = np.full((2,2), 7) 
print("A constant array: ",c)
d = np.eye(2) 
print("A 2*2 identity matrix: ",d) 
e = np.random.random((2,2)) 
print("An array with random values: ",e)

One dimensional array a =  [1 2 3]
Two dimensional array b =  [[1 2 3]
 [4 5 6]]
Size of the array:  (3,)
Element at indices 0,1,2:  1 2 3
Array after changing the element at index 0:  [5 2 3]
An array of all zeros:  [[0. 0.]
 [0. 0.]]
An array of all ones:  [[1. 1.]]
A constant array:  [[7 7]
 [7 7]]
A 2*2 identity matrix:  [[1. 0.]
 [0. 1.]]
An array with random values:  [[0.98538065 0.58657687]
 [0.34461428 0.43452589]]


In [8]:
import numpy as np 
print("Array indexing: slicing") 
al = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) 
print("al = ",al) 
b= al[:2, 1:3] 
print("Subarray consisting of first two rows and columns 1 and 2: ",b) 
b=al[1:2,:] 
print("Subarray consists of second row: ",b) 
print("Accessing columns: ") 
b=al[:,1] 
print(b,b.shape) 
c=al[:,1:2] 
print(c,c.shape) 
print("Array integer indexing: ") 
a2 = np.array([[1,2], [3, 4], [5, 6]]) 
print("a2=",a2) 
print("Example of array integer indexing: ",a2[[0, 1, 2], [0, 1, 0]]) 
print(a2[[0, 0],[1, 1]]) 
#Equivalent to the previous integer array indexing example 
print(np.array([a2[0, 1], a[0, 1]])) 
a3 = a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]) 
print("a3 = ",a3)
# Create an array of indices 
b = np.array([0, 2, 0, 1]) 
print("b= ",b)
# Select one element from each row of a using the indices in b
print("a3 = ",a3[np.arange(4), b])

 # Mutate one element from each row of a using the indices in b 
a3[np.arange(4), b] += 10
print("a3 = ",a3)
print("Boolean array indexing: ") 
a = np.array([[1,2], [3, 4], [5, 6]]) 
print("a = ",a)
bool_idx= (a > 2) 
print("Elements greater than 2: ",a[bool_idx])

Array indexing: slicing
al =  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Subarray consisting of first two rows and columns 1 and 2:  [[2 3]
 [6 7]]
Subarray consists of second row:  [[5 6 7 8]]
Accessing columns: 
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)
Array integer indexing: 
a2= [[1 2]
 [3 4]
 [5 6]]
Example of array integer indexing:  [1 4 5]
[2 2]
[2. 0.]
a3 =  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
b=  [0 2 0 1]
a3 =  [ 1  6  7 11]
a3 =  [[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]
Boolean array indexing: 
a =  [[1 2]
 [3 4]
 [5 6]]
Elements greater than 2:  [3 4 5 6]


In [9]:
import numpy as np

# Define matrices
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[6, 9], [4, 4]], dtype=np.float64)

# Print matrices
print("x =", x)
print("y =", y)

# Element-wise operations
print("Element-wise addition:", np.add(x, y))
print("Element-wise subtraction:", np.subtract(x, y))
print("Element-wise multiplication:", np.multiply(x, y))
print("Element-wise square root of x:", np.sqrt(x))

# Matrix multiplication
print("Matrix multiplication:", np.dot(x, y))

# Sums
print("Sum of all elements of matrix x:", np.sum(x))
print("Sum of elements in each column of matrix y:", np.sum(y, axis=0))
print("Sum of elements in each row of matrix y:", np.sum(y, axis=1))

# Transpose of matrix x
print("Transpose of matrix x:", x.T)


x = [[1. 2.]
 [3. 4.]]
y = [[6. 9.]
 [4. 4.]]
Element-wise addition: [[ 7. 11.]
 [ 7.  8.]]
Element-wise subtraction: [[-5. -7.]
 [-1.  0.]]
Element-wise multiplication: [[ 6. 18.]
 [12. 16.]]
Element-wise square root of x: [[1.         1.41421356]
 [1.73205081 2.        ]]
Matrix multiplication: [[14. 17.]
 [34. 43.]]
Sum of all elements of matrix x: 10.0
Sum of elements in each column of matrix y: [10. 13.]
Sum of elements in each row of matrix y: [15.  8.]
Transpose of matrix x: [[1. 3.]
 [2. 4.]]


In [10]:
import numpy as np

# Example for broadcasting
print("Example for broadcasting: ")

# Define vectors
v = np.array([1, 2, 3])
w = np.array([4, 5])

print("v =", v)
print("w =", w)

# Outer product using broadcasting
# Reshape v to (3, 1) and broadcast with w to get the outer product
print("Outer product of above vectors:")
print(np.reshape(v, (3, 1)) * w)  # Reshape v and multiply by w

# Define matrix
x = np.array([[1, 2, 3], [4, 5, 6]])

print("x =", x)

# Adding vector v to each row of matrix x
print("Resultant matrix after adding the vector v to each row of matrix x:")
print(x + v)  # Broadcasting v to each row of x

# Example for broadcasting fails
print("Example for broadcasting fails:")

print("Adding the vector w to each column matrix x will generate an error")

# Solution: Reshape w to be compatible for broadcasting
print("Solution: Reshape the matrix w then the result will be:")
print(x + np.reshape(w, (2, 1)))  # Reshape w to (2, 1) to match dimensions for broadcasting


Example for broadcasting: 
v = [1 2 3]
w = [4 5]
Outer product of above vectors:
[[ 4  5]
 [ 8 10]
 [12 15]]
x = [[1 2 3]
 [4 5 6]]
Resultant matrix after adding the vector v to each row of matrix x:
[[2 4 6]
 [5 7 9]]
Example for broadcasting fails:
Adding the vector w to each column matrix x will generate an error
Solution: Reshape the matrix w then the result will be:
[[ 5  6  7]
 [ 9 10 11]]


In [11]:
import numpy as np
from scipy.linalg import svd

# Define matrix A
A = np.array([[1, 2], [3, 4], [5, 6]])

# Print matrix A and its shape
print("A =\n", A)
print("Shape of array A:", A.shape)
print("")

# Perform Singular Value Decomposition
U, s, VT = svd(A)

# Print results of SVD
print("U =\n", U)
print("Shape of matrix U:", U.shape)
print("")

print("Sigma (diagonal matrix), s =\n", s)
print("Shape of matrix sigma:", s.shape)
print("")

print("Transpose Matrix, VT =\n", VT)
print("Shape of matrix VT:", VT.shape)


A =
 [[1 2]
 [3 4]
 [5 6]]
Shape of array A: (3, 2)

U =
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Shape of matrix U: (3, 3)

Sigma (diagonal matrix), s =
 [9.52551809 0.51430058]
Shape of matrix sigma: (2,)

Transpose Matrix, VT =
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
Shape of matrix VT: (2, 2)


In [12]:
import numpy as np
from scipy.linalg import svd

# Define matrix A
A = np.array([[1, 2], [3, 4], [5, 6]])

# Print matrix A and its shape
print("A =\n", A)
print("Shape of matrix A:", A.shape)
print("")

# Perform Singular Value Decomposition
U, s, VT = svd(A)

# Print results of SVD
print("U =\n", U)
print("Shape of matrix U:", U.shape)
print("")

print("Sigma (diagonal matrix), s =\n", s)
print("Shape of matrix s:", s.shape)
print("")

print("VT =\n", VT)
print("Shape of matrix VT:", VT.shape)
print("")

# Construct Sigma as a diagonal matrix
sigma = np.zeros((A.shape[0], A.shape[1]))
sigma[:len(s), :len(s)] = np.diag(s)

# Reconstruct the matrix B from U, Sigma, and VT
B = np.dot(U, np.dot(sigma, VT))

# Print the reconstructed matrix
print("Reconstructed matrix:\n", B)


A =
 [[1 2]
 [3 4]
 [5 6]]
Shape of matrix A: (3, 2)

U =
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Shape of matrix U: (3, 3)

Sigma (diagonal matrix), s =
 [9.52551809 0.51430058]
Shape of matrix s: (2,)

VT =
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
Shape of matrix VT: (2, 2)

Reconstructed matrix:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]


In [13]:
import numpy as np
from scipy.linalg import pinv
from numpy.linalg import svd

# Define matrix A
A = np.array([[1, 2], [3, 4], [5, 6]])

# Print matrix A
print("A =\n", A)

# Compute pseudoinverse using scipy's pinv function
print("Pseudoinverse of matrix A calculated by function pinv is:\n", pinv(A))

# Perform Singular Value Decomposition
U, s, VT = svd(A)

# Compute pseudoinverse manually
# Create the diagonal matrix D with reciprocal of non-zero singular values
d = 1.0 / s
D = np.zeros(A.shape[::-1])
D[:len(s), :len(s)] = np.diag(d)

# Compute the pseudoinverse B using U, D, and VT
B = VT.T.dot(D.T).dot(U.T)

# Print the pseudoinverse computed using SVD
print("Pseudoinverse of matrix A calculated by using svd is:\n", B)


A =
 [[1 2]
 [3 4]
 [5 6]]
Pseudoinverse of matrix A calculated by function pinv is:
 [[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [14]:
import numpy as np
from scipy.linalg import pinv
from numpy.linalg import svd

# Define matrix A
A = np.array([[1, 2], [3, 4], [5, 6]])

# Print matrix A
print("A =\n", A)

# Compute pseudoinverse using scipy's pinv function
print("Pseudoinverse of matrix A calculated by function pinv is:\n", pinv(A))

# Perform Singular Value Decomposition
U, s, VT = svd(A)

# Compute pseudoinverse manually
# Create the diagonal matrix D with reciprocal of non-zero singular values
# Note: D should be (2, 3) for A (3, 2)
D = np.zeros((A.shape[1], A.shape[0]))  # D will be (2, 3)
D[:len(s), :len(s)] = np.diag(1.0 / s)

# Compute the pseudoinverse B using U, D, and VT
B = VT.T.dot(D.T).dot(U.T)

# Print the pseudoinverse computed using SVD
print("Pseudoinverse of matrix A calculated by using svd is:\n", B)



A =
 [[1 2]
 [3 4]
 [5 6]]
Pseudoinverse of matrix A calculated by function pinv is:
 [[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [15]:
import numpy as np
from scipy.linalg import pinv
from numpy.linalg import svd

# Define matrix A
A = np.array([[1, 2], [3, 4], [5, 6]])

# Print matrix A
print("A =\n", A)

# Compute pseudoinverse using scipy's pinv function
print("Pseudoinverse of matrix A calculated by function pinv is:\n", pinv(A))

# Perform Singular Value Decomposition
U, s, VT = svd(A)

# Compute pseudoinverse manually
# Create the diagonal matrix D with reciprocal of non-zero singular values
# Note: D should be (2, 3) for A (3, 2)
d = 1.0 / s
D = np.zeros((A.shape[1], A.shape[0]))  # D will be (2, 3)
D[:len(s), :len(s)] = np.diag(d)

# Compute the pseudoinverse B using U, D, and VT
B = VT.T.dot(D.T).dot(U.T)

# Print the pseudoinverse computed using SVD
print("Pseudoinverse of matrix A calculated by using svd is:\n", B)



A =
 [[1 2]
 [3 4]
 [5 6]]
Pseudoinverse of matrix A calculated by function pinv is:
 [[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)